# Generated by Django 5.0.6 on 2024-07-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Токен"),
        ),
    ]
